export const CALENDAR_NEXT_MONTH = 'CALENDAR_NEXT_MONTH';
export const CALENDAR_PREV_MONTH = 'CALENDAR_PREV_MONTH';
export const CALENDAR_SEARCH_DATE = 'CALENDAR_SEARCH_DATE';
export const FILMS_SEARCH_FILMS = 'FILMS_SEARCH_FILMS';
export const ACTIONS_LOADING_FILMS = 'ACTIONS_LOADING_FILMS';
export const ACTIONS_GO_TO_FILMS_PAGE = 'ACTIONS_GO_TO_FILMS_PAGE';